# Puerto del servidor
server.port=8080

# Conexión a la base de datos (cambia "faltauno" por el nombre de tu BD)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ¡ESTA LÍNEA ES MAGIA! Hace que Java cree la tabla 'usuarios' automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update

# Para ver las sentencias SQL en la consola (muy útil para debuggear)
spring.jpa.show-sql=true