# Puerto del servidor
server.port=8080

# Conexión a la base de datos (cambia "faltauno" por el nombre de tu BD)
spring.datasource.url=jdbc:mysql://localhost:3306/falta_uno?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=abc123.

# ¡ESTA LÍNEA ES MAGIA! Hace que Java cree la tabla 'usuarios' automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update

# Para ver las sentencias SQL en la consola (muy útil para debuggear)
spring.jpa.show-sql=true